# Generated by Django 6.0.6 on 2026-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='blog post 1'),
            preserve_default=False,
        ),
    ]
